version: '3.8'

services:
  # --- BANCO DE DADOS POSTGRESQL LOCAL ---
  postgres-db:
    image: postgres:15-alpine
    container_name: db_eventos_local
    environment:
      POSTGRES_DB: db_eventos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./eventos-api/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./eventos-api/data.sql:/docker-entrypoint-initdb.d/02-data.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db_eventos"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
